Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -93,7 +93,19 @@ jobs:
       # ------------------------
       - name: Terraform Apply (ECR Only if not exists)
         working-directory: terraform/main
-        run: terraform apply -target=aws_ecr_repository.app_repo -auto-approve
+        run: |
+          terraform apply -target=aws_ecr_repository.app_repo -auto-approve -input=false || {
+            ERR=$?
+            echo "Terraform apply failed with exit code $ERR"
+            LOG=$(terraform apply -auto-approve -input=false 2>&1 || true)
+            if echo "$LOG" | grep -q "already exists"; then
+              echo "⚠️ Resource already exists. Continuing..."
+            else
+              echo "$LOG"
+              echo "❌ Unhandled error in backend apply. Exiting."
+              exit $ERR
+            fi
+          }
 
       - name: Extract ECR Repo Name
         working-directory: terraform/main
