Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -152,12 +152,15 @@ jobs:
         working-directory: terraform/main
         run: |
           echo "🚀 Importing all existing resources into Terraform state..."
-          echo $(TF_LOG=DEBUG terraform state list)
           resources=$(terraform state list)
-          echo $resources
           for resource in $resources; do
             echo "Importing resource: $resource"
-            TF_LOG=DEBUG terraform import $resource $(terraform state show -no-color $resource | grep 'id =' | awk '{print $3}') || echo "Resource $resource already exists in state"
+            resource_id=$(terraform state show -no-color $resource | grep 'id =' | awk '{print $3}')
+            if [ -n "$resource_id" ]; then
+              terraform import $resource $resource_id || echo "Resource $resource already exists in state"
+            else
+              echo "Failed to extract id for $resource, skipping..."
+            fi
           done
           
       # ------------------------
